### ISSUE TITLE
Batch process creation fails if the manifest file is in a folder beneath the bucket root

### ISSUE THREAD

**Issue by sjchristian** [alexdebrie/serverless-s3-batch#1]
If the manifest location is provided in a path with a slash in it beyond the initial bucket separator e.g. `s3://my-bucket/manifests/manifest.json`, job creation fails.

**Comment by jayai2014** [comment]
Any update?

**Comment by alexdebrie** [comment]
@sjchristian @jayai2014 This should be fixed now. Sorry for the wait on it!
